[DEFAULT]
# set default parameters like ploidy of the individual
ploidy = 2

[PREPARING_HIFI_READS]
# variables which determine if we want to filter hifi reads first or not
filter_hifi_reads = False
hifiadapterfiltDB_path = /path/to/hifiadapterfiltDB

[HIFIASM]
hifi_reads = /path/to/bam/files/dir
hic1_reads = /path/to/HiC1_reads/dir # you can have more than one file in the directory for any given sample and it will be merged
hic2_reads = /path/to/HiC2_reads/dir
homcov = 1
use_genomescope_homcov = False

[QUALITY_CONTROL]
compleasm_download_path = /path/to/lineage/dir
compleasm_lineage = brassicales
compleasm_odb = odb12

[SCAFFOLDING]
telomere_motif = TTTAGGG

[SLURM_ARGS]
# set mem (inMb), tmpdir, runtime (in minutes), allocation for jobs submitted
cpus_per_task = 16
mem_Mb = 32000
runtime = 120
slurm_partition = pelle
slurm_account = slu2026-1-5
tmpdir = /scratch
